// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsI5_RIbEQ8w0jQ6r-M2zP4A_qqJN0Y00',
    appId: '1:522245058665:android:c6f0ee53207e601631f2f8',
    messagingSenderId: '522245058665',
    projectId: 'chasky-taxi-ef1b3',
    databaseURL: 'https://chasky-taxi-ef1b3-default-rtdb.firebaseio.com',
    storageBucket: 'chasky-taxi-ef1b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnmYpy_lIHV9Chr6giuoEu3HAM0ThN5eU',
    appId: '1:522245058665:ios:7628a425c7332c5531f2f8',
    messagingSenderId: '522245058665',
    projectId: 'chasky-taxi-ef1b3',
    databaseURL: 'https://chasky-taxi-ef1b3-default-rtdb.firebaseio.com',
    storageBucket: 'chasky-taxi-ef1b3.appspot.com',
    androidClientId: '522245058665-ndap9to54jvp7q8lnhml2kimuitlf2ft.apps.googleusercontent.com',
    iosClientId: '522245058665-lbuqrpj9986d9veqg0p8bnsl9cefabva.apps.googleusercontent.com',
    iosBundleId: 'com.goride.driver',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwUJZ2RhrU22ge1-kzOFE1HpIkYRc-7MI',
    appId: '1:522245058665:web:e31f749b7f32623a31f2f8',
    messagingSenderId: '522245058665',
    projectId: 'chasky-taxi-ef1b3',
    authDomain: 'chasky-taxi-ef1b3.firebaseapp.com',
    databaseURL: 'https://chasky-taxi-ef1b3-default-rtdb.firebaseio.com',
    storageBucket: 'chasky-taxi-ef1b3.appspot.com',
    measurementId: 'G-95NEPWG1M3',
  );

}